# Generated by Django 5.1 on 2024-09-01 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agriculture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('optimal_growing_season', models.CharField(max_length=50)),
                ('expected_yield_per_acre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_value_per_ton', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sustainability_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('loan_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('crops', models.ManyToManyField(related_name='farmers', to='agriculture.crop')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_invested', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agriculture.farmer')),
            ],
        ),
    ]
