# Generated by Django 5.1 on 2024-09-01 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='crop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agriculture.crop'),
        ),
    ]
